experiment_name: scaling_parameters-resnet-base
base_config: ../scaling_parameters-base.yaml


data_filters:
    set_filters:

        backbone_arch_family:
            - ResNet
            - ResNetFlex

    combine_arch_families: True