experiment_name: scaling_parameters-resnet-things_eeg1
base_config: resnet-base.yaml


data_filters:
    set_filters:
        benchmark_name:
            - things_eeg1


experiment_description: >
    ""