experiment_name: mapping-things_fmri-attention_shared
base_config: ../mapping-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - things_fmri
            
        probe_type:
            - attention_shared


experiment_description: >
    ""