experiment_name: mapping-things_eeg2-attention_shared
base_config: ../mapping-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - things_eeg2

        probe_type:
            - attention_shared


experiment_description: >
    ""