experiment_name: mapping-tvsd-attention_shared
base_config: ../mapping-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - tvsd

        probe_type:
            - attention_shared


experiment_description: >
    ""