# Model
device: 'gpu'
drop_path_rate: 0.0
layer_scale_init_value: 1e-4
model_ema: True
model_ema_decay: 0.9999
model_ema_eval: True
compile_mode: 'None'
# channels_last: True

# Optimizer & LR scheme
loss_fn: 'multiclass_bce'
max_duration: '300ep'
batch_size: 512
opt: 'adamw'
lr: 3e-3
min_lr: 1e-5
lr_scheduler: 'cosineannealinglrwithwarmup'
lr_warmup_duration: '5ep'
weight_decay: 0.02
opt_betas: [0.9, 0.999]
opt_eps: 1e-8
clip_grad: 1.0
label_smoothing: 0.0
accumulation_steps: 1
target_batch_size: 2048

# Data
data_path: './data/imagenet/'
dataset: 'imagenet'
num_classes: 1000
workers: 16
pin_memory: True
train_samples: 0
repeated_aug: True
seed: 0

# Augmentation
transform_lib: 'albumentations'
albumentations_aug_set: 'ThreeAugment'
train_crop_size: 224
val_resize_size: 256
val_crop_size: 224
interpolation: bicubic
color_jitter: 0.3
aa: None
re_prob: 0.0
re_mode: pixel
re_count: 1

# MixUp / CutMix
mixup: 0.8
cutmix: 1.0
# cutmix_minmax: None
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: 'batch'


# Misc
disable_progress_bar: False
lr_monitor: False
log_interval: "1ba"

# Logging
eval_interval: '1ep'
# run_name: ' # Should be defined model-wise
save_dir: './outputs/'

