experiment_name: scaling_samples-convnext-base
base_config: ../scaling_samples-base.yaml


data_filters:
    set_filters:

        backbone_arch_family:
            - ConvNeXt
            # - ConvNeXtFlex

    combine_arch_families: False