experiment_name: scaling_samples-cornet-nsd
base_config: cornet-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - nsd_func1pt8mm_individualROIs


experiment_description: >
    ""