experiment_name: finetuning-f_things_eeg2-b_things_eeg1
base_config: things_eeg2-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - things_eeg1


experiment_description: >
    ""