experiment_name: scaling_parameters-convnext-things_meg
base_config: convnext-base.yaml


data_filters:
    set_filters:
        benchmark_name:
            - things_meg


experiment_description: >
    ""