# Model
arch: cornet_s
device: 'gpu'
compile_mode: 'default'
# channels_last: True
backbone_source: spvvs

feat_layers:
  spvvs:
    - V1
    - V2
    - V4
    - IT

# Optimizer & LR scheme
max_epochs: 100
batch_size_image: 512
batch_size_neural: 256
opt: 'adamw'
lr_encoder: 1e-5
lr_decoder: 1e-3
lr_scheduler: 'cosineannealinglrwarmup'
lr_warmup_duration: 5
momentum: 0.9
wd_encoder: 0.05
wd_decoder: 1e-1




# Data
data_path: './data/imagenet/'
workers: 16
pin_memory: True
train_samples: 0
seed: 0


# Data
data_path: './data/imagenet/'
workers: 16
pin_memory: True
seed: 0

# Resizing
val_resize_size: 256
val_crop_size: 224
train_crop_size: 224

# Misc
disable_progress_bar: False
lr_monitor: False

# Logging
eval_interval: 1
# run_name: 'cornet_s_imagenet_full'

