experiment_name: scaling_samples-architecture_average-base
base_config: ../scaling_samples-base.yaml

data_filters:
    set_filters:

        backbone_arch_family:
            - AlexNet
            - CORnet-S
            - EfficientNet
            - ResNet
            # - ResNetFlex
            - ConvNeXt
            # - ConvNeXtFlex
            - ViT
            # - ViTFlex

    combine_arch_families: False