experiment_name: scaling_samples-architecture_average-things_meg
base_config: architecture_average-base.yaml


data_filters:
    set_filters:
        benchmark_name:
            - things_meg


experiment_description: >
    ""