experiment_name: finetuning-f_things_meg-b_things_eeg1
base_config: things_meg-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - things_eeg1


experiment_description: >
    ""