experiment_name: finetuning-f_things_meg-base
base_config: ../finetuning-base.yaml

data_filters:
    set_filters:
        finetuning_dataset:
            - things_meg

experiment_description: >
    ""