experiment_name: finetuning-f_nsd-base
base_config: ../finetuning-base.yaml

data_filters:
    set_filters:
        finetuning_dataset:
            - nsd_func1pt8mm_individualROIs

experiment_description: >
    ""