# Model
arch: resnet50
device: 'gpu'

# Optimizer & LR scheme
max_duration: '100ep'
batch_size: 256
opt: 'sgd'
lr: 0.1
lr_scheduler: 'cosineannealinglrwithwarmup'
lr_warmup_duration: '5ep'
momentum: 0.9
weight_decay: 1e-4


# Data
data_path: './data/imagenet/'
workers: 32
pin_memory: True
train_samples: 0
seed: 0

# Resizing
val_resize_size: 256
val_crop_size: 224
train_crop_size: 224

# Misc
disable_progress_bar: False

# Logging
eval_interval: '1ep'
run_name: 'resnet50_imagenet_full'
save_dir: './outputs/'

