lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
lora_bias: "none"
lora_target_modules: 
    - "qkv"
    - "fc1"
    - "fc2"
lora_modules_to_save: 
    - "backbone.head"
lora_exclude_modules:
    - "decoders"
    - "projectors"