experiment_name: mapping-things_fmri-linear
base_config: ../mapping-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - things_fmri
            
        probe_type:
            - linear_individual


experiment_description: >
    ""