experiment_name: mapping-things_meg-linear
base_config: ../mapping-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - things_meg

        probe_type:
            - linear_individual


experiment_description: >
    ""