experiment_name: mapping-things_eeg2-linear
base_config: ../mapping-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - things_eeg2

        probe_type:
            - linear_individual


experiment_description: >
    ""