experiment_name: scaling_parameters-efficientnet-bs_mh
base_config: efficientnet-base.yaml

data_filters:
    set_filters:
        benchmark_name:
            - bs_mh


experiment_description: >
    ""