experiment_name: scaling_parameters-architecture_average-base
base_config: ../scaling_parameters-base.yaml

data_filters:
    set_filters:

        backbone_arch_family:
            - AlexNet
            - CORnet-S
            - EfficientNet
            - ResNet
            - ResNetFlex
            - ConvNeXt
            - ConvNeXtFlex
            - ViT
            - ViTFlex

    combine_arch_families: True