experiment_name: finetuning-f_things_eeg1-base
base_config: ../finetuning-base.yaml

data_filters:
    set_filters:
        finetuning_dataset:
            - things_eeg1

experiment_description: >
    ""