experiment_name: scaling_compute-convnext-base
base_config: ../scaling_compute-base.yaml


data_filters:
    set_filters:

        backbone_arch_family:
            - ConvNeXt
            - ConvNeXtFlex

    combine_arch_families: True